;; Generated by :claw at 2021-04-24T14:54:47.952777+03:00
(asdf:defsystem #:claw-olm-bindings
  :description "Bindings generated by claw-olm/wrapper"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))