;; Generated by :claw at 2021-02-14T17:51:38.119931+03:00
(asdf:defsystem #:claw-olm-bindings
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :claw-utils)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature
    (:and :x86-64 :linux))))